const express = require('express')
const path = require('path')
const cookieParser = require('cookie-parser')
const PORT = process.env.PORT || 8903

express()
  .use(express.json())
  .use(express.urlencoded({extended: true}))
  .use(express.static(path.join(__dirname, 'public')))
  .set('views', path.join(__dirname, 'views'))
  .set('view engine', 'ejs')
  .get('/', (req, res) => res.render('index'))
  .get('/blog', (req, res) => res.render('blog'))
  .get('/post1', (req, res) => res.render('post1'))
  .get('/post2', (req, res) => res.render('post2'))
  .listen(PORT, () => console.log(`Listening on ${ PORT }`))
